//go:build linux || darwin

package installer

import (
	"os"
	"path/filepath"
	"strings"
)

// ConfigureShell configures the Unix shell rc file with DevScripts settings.
// Returns the rc file path and any error.
func ConfigureShell(installDir string) (string, error) {
	rcFile := detectRCFile()

	// Read existing content
	existing := ""
	if data, err := os.ReadFile(rcFile); err == nil {
		existing = string(data)
	}

	// Remove old DevScripts block
	existing = removeBlock(existing, "# DevScripts Installer", "# End DevScripts Installer")

	// Build new block
	block := buildUnixBlock(installDir)

	content := strings.TrimRight(existing, "\n") + "\n\n" + block + "\n"
	if strings.TrimSpace(existing) == "" {
		content = block + "\n"
	}

	if err := os.MkdirAll(filepath.Dir(rcFile), 0755); err != nil {
		return "", err
	}
	if err := os.WriteFile(rcFile, []byte(content), 0644); err != nil {
		return "", err
	}

	return rcFile, nil
}

func detectRCFile() string {
	home, _ := os.UserHomeDir()
	shell := os.Getenv("SHELL")

	switch {
	case strings.Contains(shell, "zsh"):
		return filepath.Join(home, ".zshrc")
	case strings.Contains(shell, "bash"):
		return filepath.Join(home, ".bashrc")
	}

	// Fallback: check which files exist
	for _, f := range []string{".zshrc", ".bashrc"} {
		path := filepath.Join(home, f)
		if _, err := os.Stat(path); err == nil {
			return path
		}
	}
	return filepath.Join(home, ".bashrc")
}

// RemoveShellConfig removes the DevScripts block from the Unix shell rc file.
// Returns the rc file path and any error.
func RemoveShellConfig() (string, error) {
	rcFile := detectRCFile()
	data, err := os.ReadFile(rcFile)
	if os.IsNotExist(err) {
		return rcFile, nil
	}
	if err != nil {
		return "", err
	}
	cleaned := removeBlock(string(data), "# DevScripts Installer", "# End DevScripts Installer")
	cleaned = strings.TrimRight(cleaned, "\n") + "\n"
	return rcFile, os.WriteFile(rcFile, []byte(cleaned), 0644)
}

func buildUnixBlock(installDir string) string {
	return `# DevScripts Installer
# Auto-generated by installer
export DEVSCRIPTS_ROOT="` + installDir + `"
export PATH="$PATH:$DEVSCRIPTS_ROOT"

alias devlauncher="$DEVSCRIPTS_ROOT/launcher"
alias dl="devlauncher"

devscript() {
    if [ -z "$1" ]; then
        echo "Uso: devscript <nombre_script>"
        return 1
    fi
    local script=$(find "$DEVSCRIPTS_ROOT/scripts" -type f -name "$1" ! -path "*/lib/*" | head -n1)
    if [ -z "$script" ]; then echo "Script no encontrado: $1"; return 1; fi
    echo "Ejecutando: $script"
    bash "$script" "${@:2}"
}
# End DevScripts Installer`
}

// removeBlock removes lines between (and including) startMarker and endMarker.
func removeBlock(content, startMarker, endMarker string) string {
	lines := strings.Split(content, "\n")
	var result []string
	inBlock := false
	for _, line := range lines {
		if strings.Contains(line, startMarker) {
			inBlock = true
			continue
		}
		if inBlock {
			if strings.Contains(line, endMarker) {
				inBlock = false
			}
			continue
		}
		result = append(result, line)
	}
	return strings.Join(result, "\n")
}
