//go:build windows

package installer

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// ConfigureShell configures both Windows PowerShell and PowerShell 7 profiles
// with DevScripts settings.
// Returns the written profile paths and any error.
func ConfigureShell(installDir string) (string, error) {
	profilePaths, err := getWindowsProfilePaths()
	if err != nil {
		return "", err
	}

	block := buildPowerShellBlock(installDir)
	written := make([]string, 0, len(profilePaths))

	for _, profilePath := range profilePaths {
		if err := os.MkdirAll(filepath.Dir(profilePath), 0755); err != nil {
			return "", err
		}

		existing := ""
		if data, err := os.ReadFile(profilePath); err == nil {
			existing = string(data)
		}

		existing = removeBlock(existing, "# DevScripts Installer", "# End DevScripts Installer")

		content := strings.TrimRight(existing, "\n\r") + "\n\n" + block + "\n"
		if strings.TrimSpace(existing) == "" {
			content = block + "\n"
		}

		if err := os.WriteFile(profilePath, []byte(content), 0644); err != nil {
			return "", err
		}

		written = append(written, profilePath)
	}

	return strings.Join(written, ", "), nil
}

// RemoveShellConfig removes the DevScripts block from both Windows PowerShell
// and PowerShell 7 profiles,
// and cleans DEVSCRIPTS_ROOT + install dir from the user registry PATH.
// Returns the cleaned profile paths and any error.
func RemoveShellConfig() (string, error) {
	profilePaths, err := getWindowsProfilePaths()
	if err != nil {
		return "", err
	}
	cleanedPaths := make([]string, 0, len(profilePaths))

	for _, profilePath := range profilePaths {
		data, err := os.ReadFile(profilePath)
		if os.IsNotExist(err) {
			cleanedPaths = append(cleanedPaths, profilePath)
			continue
		}
		if err != nil {
			return "", err
		}

		cleaned := removeBlock(string(data), "# DevScripts Installer", "# End DevScripts Installer")
		cleaned = strings.TrimRight(cleaned, "\n\r") + "\n"
		if err := os.WriteFile(profilePath, []byte(cleaned), 0644); err != nil {
			return strings.Join(cleanedPaths, ", "), err
		}

		cleanedPaths = append(cleanedPaths, profilePath)
	}

	// Remove DEVSCRIPTS_ROOT and its path from the user registry environment.
	installDir := GetInstallDir()
	_ = removeFromRegistryEnv(installDir)

	return strings.Join(cleanedPaths, ", "), nil
}

func getWindowsProfilePaths() ([]string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, err
	}

	paths := []string{
		filepath.Join(home, "Documents", "WindowsPowerShell", "profile.ps1"),
		filepath.Join(home, "Documents", "PowerShell", "profile.ps1"),
	}

	seen := make(map[string]struct{}, len(paths))
	unique := make([]string, 0, len(paths))
	for _, p := range paths {
		norm := strings.ToLower(filepath.Clean(p))
		if _, ok := seen[norm]; ok {
			continue
		}
		seen[norm] = struct{}{}
		unique = append(unique, p)
	}

	return unique, nil
}

// removeFromRegistryEnv removes DEVSCRIPTS_ROOT from user env and strips any
// DevLauncher/devscripts-related entries from the user's permanent PATH in the registry.
func removeFromRegistryEnv(installDir string) error {
	script := `
$installDir = "` + installDir + `"
# Remove DEVSCRIPTS_ROOT from user environment
[System.Environment]::SetEnvironmentVariable("DEVSCRIPTS_ROOT", $null, "User")
# Strip install dir and any *.devlauncher* or *devscripts* entries from user PATH
$path = [System.Environment]::GetEnvironmentVariable("PATH", "User")
if ($path) {
    $parts = $path -split ";" |
        Where-Object { $_ -ne "" -and
                       $_.ToLower() -ne $installDir.ToLower() -and
					   $_ -notlike "*\\.devlauncher*" -and
					   $_ -notlike "*/.devlauncher*" -and
                       $_ -notlike "*\devscripts*" -and
                       $_ -notlike "*/.devscripts*" }
    [System.Environment]::SetEnvironmentVariable("PATH", ($parts -join ";"), "User")
}
`
	cmd := exec.Command("powershell", "-NoProfile", "-Command", script)
	return cmd.Run()
}

func buildPowerShellBlock(installDir string) string {
	return `# DevScripts Installer
# Auto-generated by installer
$env:DEVSCRIPTS_ROOT = "` + installDir + `"
$env:PATH += ";$env:DEVSCRIPTS_ROOT"

function devlauncher {
    & "$env:DEVSCRIPTS_ROOT\launcher.exe" @args
}
Set-Alias -Name dl -Value devlauncher

function devscript {
    param(
        [Parameter(Mandatory=$false)]
        [string]$ScriptName,
        [Parameter(ValueFromRemainingArguments=$true)]
        [string[]]$Arguments
    )
    if (-not $ScriptName) {
        Write-Host "Uso: devscript <nombre_script>"
        return
    }
    $searchPath = Join-Path "$env:DEVSCRIPTS_ROOT" "scripts\win"
    $script = Get-ChildItem -Path $searchPath -Recurse -File -Filter $ScriptName -ErrorAction SilentlyContinue |
               Where-Object { $_.DirectoryName -notmatch '\\lib$' } |
               Select-Object -First 1
    if (-not $script) { Write-Host "Script no encontrado: $ScriptName"; return }
    Write-Host "Ejecutando: $($script.FullName)"
    if ($script.Extension -eq '.ps1') { & $script.FullName @Arguments }
    elseif ($script.Extension -eq '.bat') { cmd.exe /c $script.FullName @Arguments }
}
# End DevScripts Installer`
}

// removeBlock removes lines between (and including) startMarker and endMarker.
func removeBlock(content, startMarker, endMarker string) string {
	lines := strings.Split(content, "\n")
	var result []string
	inBlock := false
	for _, line := range lines {
		if strings.Contains(line, startMarker) {
			inBlock = true
			continue
		}
		if inBlock {
			if strings.Contains(line, endMarker) {
				inBlock = false
			}
			continue
		}
		result = append(result, line)
	}
	return strings.Join(result, "\n")
}
