//go:build windows

package installer

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// ConfigureShell configures PowerShell profile with DevScripts settings.
// Returns the profile path and any error.
func ConfigureShell(installDir string) (string, error) {
	// Get $PROFILE.CurrentUserAllHosts path
	cmd := exec.Command("powershell", "-NoProfile", "-Command", "$PROFILE.CurrentUserAllHosts")
	out, err := cmd.Output()
	if err != nil {
		return "", err
	}
	profilePath := strings.TrimSpace(string(out))

	// Create profile directory if needed
	if err := os.MkdirAll(filepath.Dir(profilePath), 0755); err != nil {
		return "", err
	}

	// Read existing profile content
	existing := ""
	if data, err := os.ReadFile(profilePath); err == nil {
		existing = string(data)
	}

	// Remove old DevScripts block if present
	existing = removeBlock(existing, "# DevScripts Installer", "# End DevScripts Installer")

	// Build new config block
	block := buildPowerShellBlock(installDir)

	// Append new block
	content := strings.TrimRight(existing, "\n\r") + "\n\n" + block + "\n"
	if strings.TrimSpace(existing) == "" {
		content = block + "\n"
	}

	if err := os.WriteFile(profilePath, []byte(content), 0644); err != nil {
		return "", err
	}

	return profilePath, nil
}

// RemoveShellConfig removes the DevScripts block from the PowerShell profile.
// Returns the profile path and any error.
func RemoveShellConfig() (string, error) {
	cmd := exec.Command("powershell", "-NoProfile", "-Command", "$PROFILE.CurrentUserAllHosts")
	out, err := cmd.Output()
	if err != nil {
		return "", err
	}
	profilePath := strings.TrimSpace(string(out))

	data, err := os.ReadFile(profilePath)
	if os.IsNotExist(err) {
		return profilePath, nil // nothing to do
	}
	if err != nil {
		return "", err
	}

	cleaned := removeBlock(string(data), "# DevScripts Installer", "# End DevScripts Installer")
	cleaned = strings.TrimRight(cleaned, "\n\r") + "\n"
	return profilePath, os.WriteFile(profilePath, []byte(cleaned), 0644)
}

func buildPowerShellBlock(installDir string) string {
	return `# DevScripts Installer
# Auto-generated by installer
$env:DEVSCRIPTS_ROOT = "` + installDir + `"
$env:PATH += ";$env:DEVSCRIPTS_ROOT"

function devlauncher {
    & "$env:DEVSCRIPTS_ROOT\launcher.exe" @args
}
Set-Alias -Name dl -Value devlauncher

function devscript {
    param(
        [Parameter(Mandatory=$false)]
        [string]$ScriptName,
        [Parameter(ValueFromRemainingArguments=$true)]
        [string[]]$Arguments
    )
    if (-not $ScriptName) {
        Write-Host "Uso: devscript <nombre_script>"
        return
    }
    $searchPath = Join-Path "$env:DEVSCRIPTS_ROOT" "scripts\win"
    $script = Get-ChildItem -Path $searchPath -Recurse -File -Filter $ScriptName -ErrorAction SilentlyContinue |
               Where-Object { $_.DirectoryName -notmatch '\\lib$' } |
               Select-Object -First 1
    if (-not $script) { Write-Host "Script no encontrado: $ScriptName"; return }
    Write-Host "Ejecutando: $($script.FullName)"
    if ($script.Extension -eq '.ps1') { & $script.FullName @Arguments }
    elseif ($script.Extension -eq '.bat') { cmd.exe /c $script.FullName @Arguments }
}
# End DevScripts Installer`
}

// removeBlock removes lines between (and including) startMarker and endMarker.
func removeBlock(content, startMarker, endMarker string) string {
	lines := strings.Split(content, "\n")
	var result []string
	inBlock := false
	for _, line := range lines {
		if strings.Contains(line, startMarker) {
			inBlock = true
			continue
		}
		if inBlock {
			if strings.Contains(line, endMarker) {
				inBlock = false
			}
			continue
		}
		result = append(result, line)
	}
	return strings.Join(result, "\n")
}
