//go:build windows

package installer

import (
	"os"
	"path/filepath"
)

func GenerateUninstaller(installDir string) error {
	content := `# Auto-generated by DevLauncher installer
$ErrorActionPreference = "Stop"

$installDir = Split-Path -Parent $MyInvocation.MyCommand.Path

try {
    $profilePath = $PROFILE.CurrentUserAllHosts
    if (Test-Path $profilePath) {
        $raw = Get-Content $profilePath -Raw
        $clean = [System.Text.RegularExpressions.Regex]::Replace($raw, '(?s)# DevScripts Installer.*?# End DevScripts Installer\s*', '')
        Set-Content -Path $profilePath -Value $clean -Encoding UTF8
    }
} catch {}

try {
    [System.Environment]::SetEnvironmentVariable("DEVSCRIPTS_ROOT", $null, "User")
    $path = [System.Environment]::GetEnvironmentVariable("PATH", "User")
    if ($path) {
        $parts = $path -split ";" |
            Where-Object { $_ -and $_.ToLower() -ne $installDir.ToLower() -and $_ -notlike "*\devscripts*" -and $_ -notlike "*/.devscripts*" }
        [System.Environment]::SetEnvironmentVariable("PATH", ($parts -join ";"), "User")
    }
} catch {}

Write-Host "Desinstalación en curso..."
Start-Process -FilePath "cmd.exe" -ArgumentList "/c timeout /t 1 >nul & rmdir /s /q \"$installDir\"" -WindowStyle Hidden
Write-Host "DevLauncher desinstalado."
`

	path := filepath.Join(installDir, "uninstaller.ps1")
	return os.WriteFile(path, []byte(content), 0644)
}
