#!/usr/bin/env bash
set -euo pipefail

# Crea en el directorio actual la misma estructura de carpetas del proyecto.
# Uso:
#   ./generar_estructura.sh
#   ./generar_estructura.sh /ruta/destino

DESTINO="${1:-.}"

DIRECTORIOS=(
  "database"
  "database/attachments"
  "database/attachments/audio"
  "database/attachments/docs"
  "database/attachments/images"
  "database/attachments/video"
  "database/data"
  "database/data/01_raw"
  "database/data/02_clean"
  "database/data/03_objects"
  "database/data/04_answers"
  "database/models"
  "dist"
  "dist/desktop"
  "dist/desktop/linux"
  "dist/desktop/mac"
  "dist/desktop/win"
  "dist/docker"
  "dist/mobile"
  "dist/mobile/android"
  "dist/mobile/ios"
  "docker"
  "docs"
  "docs/documentation"
  "docs/pdf"
  "frontend"
  "logs"
  "notebooks"
  "robots"
  "scripts"
  "src"
  "src/application"
  "src/application/event"
  "src/application/jobs"
  "src/application/pipes"
  "src/application/sandbox"
  "src/application/simulation"
  "src/application/tasks"
  "src/application/tests"
  "src/application/tests/benchmark"
  "src/application/tests/fuzzers"
  "src/application/tests/mocks"
  "src/application/tests/mutation"
  "src/core"
  "src/core/base"
  "src/core/functions"
  "src/core/rules"
  "src/core/tests"
  "src/core/tests/benchmark"
  "src/core/tests/fuzzers"
  "src/core/tests/mocks"
  "src/core/tests/mutation"
  "src/core/types"
  "src/core/utils"
  "src/middleware"
  "src/middleware/api"
  "src/middleware/backend"
  "src/middleware/browser"
  "src/middleware/config"
  "src/middleware/connection"
  "src/middleware/controller"
  "src/middleware/i18n"
  "src/middleware/interfaces"
  "src/middleware/queue"
  "src/middleware/servers"
  "src/middleware/tests"
  "src/middleware/tests/benchmark"
  "src/middleware/tests/fuzzers"
  "src/middleware/tests/mocks"
  "src/middleware/tests/mutation"
  "src/middleware/types"
  "src/modules"
)

for dir in "${DIRECTORIOS[@]}"; do
  mkdir -p "${DESTINO%/}/$dir"
done

echo "Estructura creada en: ${DESTINO%/}"
